### ISSUE TITLE
Sanitize URLs by Removing Query Strings

### ISSUE THREAD

**Issue by vo1dee** [vo1dee/PsychochauffeurBot#16]
## Problem Statement
Links containing query strings, such as `?s=46`, need to be sanitized to ensure that only the main URL path is shared or processed. This helps in maintaining consistency and clarity in the URLs being used across our application.

For example, a URL like `https://x.com/kit_polyoviy/status/1870753127189839874?s=46` should be sanitized to `https://x.com/kit_polyoviy/status/1870753127189839874` and then send to modified_links for processing.

## Proposed Solution
Implement a function that processes a given URL and removes any query string components, returning the sanitized version of the URL. This function should be utilized wherever URL sanitization is required.

## Task List
- [ ] Develop a URL sanitization function.
- [ ] Integrate this functionality into the relevant part of the application.
- [ ] Test the sanitization function with various URL scenarios to ensure it handles all edge cases.

### Additional Context
This change is aimed at improving the user experience by ensuring URLs are clean and free of unnecessary parameters, which could otherwise clutter the display or lead to unintended tracking or errors.

**Example:**
Input: `https://x.com/kit_polyoviy/status/1870753127189839874?s=46`  
Output: `https://fixupx.com/kit_polyoviy/status/1870753127189839874`

**Comment by saajann** [comment]
I wanted to work on this but you arrived first

**Comment by vo1dee** [comment]
> Fixed.
> 
> from urllib.parse import urlparse, urlunparse
> 
> def sanitize_url(url: str, replace_domain: str = None) -> str:
> 
> ```
> parsed_url = urlparse(url)
> netloc = replace_domain if replace_domain else parsed_url.netloc
> sanitized_url = urlunparse((parsed_url.scheme, netloc, parsed_url.path, '', '', ''))
> return sanitized_url
> ```

Thanks

**Comment by MiguelZabarain** [comment]
It was an easy one to work on for my first contribution ever. Good for you @cyber-vv.

**Comment by vo1dee** [comment]
appretiate your help guys.
fixed with commit https://github.com/vo1dee/PsychochauffeurBot/commit/5873797f27d51f1de7d6985241337f5d68b82e14
